function getQuizByLevelNumber(levelNum) {
    switch (levelNum) {
        case 1:
            return level01;
        case 2:
            return level02;
        case 3:
            return level03;
        case 4:
            return level04;
        case 5:
            return level05;
        case 6:
            return level06;
        case 7:
            return level07;
        case 8:
            return level08;
        case 9:
            return level09;
        case 10:
            return level10;
        case 11:
            return level11;
        case 12:
            return level12;
        case 13:
            return level13;
        case 14:
            return level14;
        case 15:
            return level15;
        case 16:
            return level16;
        case 17:
            return level17;
        case 18:
            return level18;
        case 19:
            return level19;
        case 20:
            return level20;
        case 21:
            return level21;
        case 22:
            return level22;
        case 23:
            return level23;
        case 24:
            return level24;
        case 25:
            return level25;
        case 26:
            return level26;
        case 27:
            return level27;
        case 28:
            return level28;
        case 29:
            return level29;
        case 30:
            return level30;
        case 31:
            return level31;
        default:
            return null;
    }
}